# GitHub Actions CI/CD Workflow for Docker Compose

name: Docker Compose CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker-compose-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start and build containers with Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yaml
          command: up
          args: -d --build

      - name: Wait for services to start
        run: sleep 30

      - name: Verify frontend is accessible
        run: curl --fail http://localhost:3000 || exit 1

      - name: Shut down containers
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yaml
          command: down