# GitHub Actions CI/CD Workflow for Docker Compose

# .github/workflows/docker-compose-ci.yml
name: Docker Compose CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker-compose-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0

      - name: Build and run containers
        run: docker-compose -f docker-compose.yaml up -d --build

      - name: Wait for services to start
        run: sleep 30

      - name: Verify backend is running
        run: curl --fail http://localhost || exit 1

      - name: Verify frontend is accessible
        run: curl --fail http://localhost:3000 || exit 1
      
      - name: Shut down containers
        run: docker-compose down